### ISSUE TITLE
Add a paper please

### ISSUE THREAD

**Issue by GGrain** [program-repair/program-repair.github.io#101]
I would like to add the following publication:
K. Huang, S. Yang, H. Sun, C. Sun, X. Li and Y. Zhang, "Repairing Security Vulnerabilities Using Pre-trained Programming Language Models," 2022 52nd Annual IEEE/IFIP International Conference on Dependable Systems and Networks Workshops (DSN-W), Baltimore, MD, USA, 2022, pp. 111-116, doi: 10.1109/DSN-W54100.2022.00027.

**Comment by mechtaev** [comment]
Thanks, added in [bcfd9cf](https://github.com/program-repair/program-repair.github.io/commit/bcfd9cfcd31f474057034a8f7d0d27c504596086)
