### ISSUE TITLE
Request : add this APR research.

### ISSUE THREAD

**Issue by kimjisung78** [program-repair/program-repair.github.io#102]
I would like to add the following publication:
J. Kim and B. Lee, "MCRepair: Multi-Chunk Program Repair via Patch Optimization with Buggy Block," In Proceedings of the ACM SIGAPP 38th Symposium on Applied Computing (SAC), ACM, New York, NY, USA, 2023, p.p. 1508–1515. 

- DBLP key: [https://doi.org/10.1145/3555776.3577762](https://doi.org/10.1145/3555776.3577762)

**Comment by mechtaev** [comment]
Thanks,  added in [7a12b29](https://github.com/program-repair/program-repair.github.io/commit/7a12b296d9d73ace25049d59264c9e46033b5029)
