### ISSUE TITLE
CoCoNut

### ISSUE THREAD

**Issue by DZimo** [program-repair/program-repair.github.io#106]
I would like to add the following tool:

- Name: CoCoNut
- One line description: Combining context-aware neural translation models using ensemble for program repair
- Target: Java, C, Python, and JavaScript
- DBPL key: conf/issta/LutellierPPLW020
- Website: https://dl.acm.org/doi/10.1145/3395363.3397369
- Repository (optional): https://github.com/lin-tan/CoCoNut-Artifact

**Comment by mechtaev** [comment]
Thanks, added in [eedc0c5](https://github.com/program-repair/program-repair.github.io/commit/eedc0c578033e9d70dd0cba3fae0933faf47ddd5)
