### ISSUE TITLE
Add benchmark growingBugs

### ISSUE THREAD

**Issue by jiangyanjie** [program-repair/program-repair.github.io#108]
I would like to add the following benchmark:

- Name: growingBugs
- One line description: A benchmark for Java defects providing easy-to-use interfaces similar to Defects4J
- Target: Java
- DBPL key: journals/tse/JiangLLZCNZHBZ23
- Website: https://github.com/liuhuigmail/GrowingBugRepository
- Repository (optional):

**Comment by mechtaev** [comment]
Thanks! Added in a8d4b034e9c0f3878eed9cc76173064218d78ba9.
