### ISSUE TITLE
Minecraft: Automated Mining of Software Bug Fixes with Precise Code Context

### ISSUE THREAD

**Issue by shouvick149** [program-repair/program-repair.github.io#110]
I would like to add the following benchmark:

- Name: Minecraft: Automated Mining of Software Bug Fixes with Precise Code Context
- One line description: Automated Mining of Software Bug Fixes with Precise Code Context
- Target: [C/C++, Java, Python]
- DBPL key: [conf/kbse/AvulaVM23]
- Website: https://github.com/SET-IITGN/Minecraft
- Repository (optional): https://github.com/SET-IITGN/Minecraft

**Comment by mechtaev** [comment]
Thanks! Added in a8d4b034e9c0f3878eed9cc76173064218d78ba9.
