### ISSUE TITLE
add PyGGI for repair and improvement of programs in multiple languages 

### ISSUE THREAD

**Issue by justynapt** [program-repair/program-repair.github.io#114]
I would like to add the following tool:

- Name: PyGGI
- One line description: Python General Framework for Genetic Improvement
- Target: [e.g. C/C++, Java, Binaries] multiple (Java, Python, C#, C, C++, possibly other)
- DBPL key: [e.g. journals/tse/GouesNFW12] conf/sigsoft/AnBPY19
- Website: https://github.com/coinse/pyggi
- Repository (optional): https://github.com/coinse/pyggi

**Comment by mechtaev** [comment]
Thanks! Added in a8d4b034e9c0f3878eed9cc76173064218d78ba9.
