### ISSUE TITLE
Gin for repair and improvement of Java software

### ISSUE THREAD

**Issue by justynapt** [program-repair/program-repair.github.io#116]
I would like to add the following tool:

- Name: Gin
- One line description: Gin: A Tool for Experimentation with GI
- Target: Java
- DBPL key: conf/gecco/BrownleePABWW19
- Website: https://github.com/gintool/gin
- Repository (optional): https://github.com/gintool/gin

**Comment by mechtaev** [comment]
Thanks! Added in a8d4b034e9c0f3878eed9cc76173064218d78ba9.
