### ISSUE TITLE
Is this Change the Answer to that Problem? Correlating Descriptions of Bug and Code Changes for Evaluating Patch Correctness

### ISSUE THREAD

**Issue by HaoyeTianCoder** [program-repair/program-repair.github.io#119]
I would like to add the following publication:

- DBLP key: conf/kbse/TianTHW0XKB22

@inproceedings{DBLP:conf/kbse/TianTHW0XKB22,
  author       = {Haoye Tian and
                  Xunzhu Tang and
                  Andrew Habib and
                  Shangwen Wang and
                  Kui Liu and
                  Xin Xia and
                  Jacques Klein and
                  Tegawend{\'{e}} F. Bissyand{\'{e}}},
  title        = {Is this Change the Answer to that Problem?: Correlating Descriptions
                  of Bug and Code Changes for Evaluating Patch Correctness},
  booktitle    = {37th {IEEE/ACM} International Conference on Automated Software Engineering,
                  {ASE} 2022, Rochester, MI, USA, October 10-14, 2022},
  pages        = {59:1--59:13},
  publisher    = {{ACM}},
  year         = {2022},
  url          = {https://doi.org/10.1145/3551349.3556914},
  doi          = {10.1145/3551349.3556914},
  timestamp    = {Mon, 26 Jun 2023 20:39:46 +0200},
  biburl       = {https://dblp.org/rec/conf/kbse/TianTHW0XKB22.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

**Comment by mechtaev** [comment]
Thanks! Added in acedf61362c950db6fadedebba02a6cdb7baab66.
