### ISSUE TITLE
Add ExtractFix

### ISSUE THREAD

**Issue by tareq97** [program-repair/program-repair.github.io#120]
I would like to add the following tool:

- Name:ExtractFix
- One line description: Beyond Tests: Program Vulnerability Repair via Crash Constraint Extraction 
- Target: C/C++
- DBPL key: journals/tosem/GaoWDJXR21
- Website: https://extractfix.github.io/
- Repository:https://github.com/nus-apr/extractfix-benchmark

**Comment by mechtaev** [comment]
Thanks! Added in acedf61362c950db6fadedebba02a6cdb7baab66.
