### ISSUE TITLE
Add new benchmark TutorCode

### ISSUE THREAD

**Issue by buaabarty** [program-repair/program-repair.github.io#121]
I would like to add the following benchmark:

- Name: TutorCode
- One line description: 1,239 C++ buggy codes incorporating human tutor guidance and solution descriptions, accessible via API.
- Target: C/C++
- DBPL key: conf/issta/YangTPYWKBJ24
- Website: https://tutorcode.org
- Repository (optional): https://github.com/buaabarty/CREF

**Comment by mechtaev** [comment]
Thanks! Added in acedf61362c950db6fadedebba02a6cdb7baab66.
