### ISSUE TITLE
Submitting a new repair tool: SimFix

### ISSUE THREAD

**Issue by xgdsmileboy** [program-repair/program-repair.github.io#15]
{
"name": "SimFix",
"description": "Fixing Java bugs by leveraging existing patches and similar code",
"url": "https://github.com/xgdsmileboy/SimFix",
"target": "Java",
"title": "Shaping Program Repair Space with Existing Patches and Similar Code",
"authors": "Jiajun Jiang, Yingfei Xiong, Hongyu Zhang, Qing Gao, Xiangqun Chen",
"venue": "ISSTA'18: The 27th International Symposium on Software Testing and Analysis",
"year": "2018"
}

**Comment by mechtaev** [comment]
Thanks, I will add it once the paper appears at dblp.
