### ISSUE TITLE
Getafix: Learning to Fix Bugs Automatically

### ISSUE THREAD

**Issue by ovidiunitu** [program-repair/program-repair.github.io#24]
I would like to add the following publication:

- DBLP key: [e.g. journals/corr/abs-1902-06111]

**Comment by mechtaev** [comment]
Thank you, but according to current guidelines we only list peer-reviewed articles. I will wait until the paper is published, and then close the issue.

**Comment by ovidiunitu** [comment]
but is published here: [https://arxiv.org/pdf/1902.06111.pdf](url)

**Comment by mechtaev** [comment]
I meant when it is published in a peer-reviewed conference or journal

**Comment by ovidiunitu** [comment]
Ah, now is clear. Thanks

**Comment by mechtaev** [comment]
Added in 11bb846
