### ISSUE TITLE
[New publication] Compilation error repair: for the student programs, from the student programs

### ISSUE THREAD

**Issue by purushottamkar** [program-repair/program-repair.github.io#25]
I would like to add the following publication:

- DBLP key:     conf/icse/AhmedKKKG18
- DBLP link:     https://dblp.org/rec/conf/icse/AhmedKKKG18

**Comment by mechtaev** [comment]
Added in 535af26. Thanks!

**Comment by purushottamkar** [comment]
Thanks very much for including the publication
Regards
puru
