### ISSUE TITLE
kGenProg: A High-performance, High-extensibility and High-portability APR System

### ISSUE THREAD

**Issue by hnymA** [program-repair/program-repair.github.io#27]
I would like to add the following tool:

- Name: kGenProg
- One line description: automated program repair tool written in Java for Java
- Target: [e.g. C/C++, Java, Binaries] Java
- DBPL key: [e.g. journals/tse/GouesNFW12] conf/apsec/HigoMATNMTK18
- Website: https://github.com/kusumotolab/kGenProg
- Repository (optional): https://github.com/kusumotolab/kGenProg

**Comment by mechtaev** [comment]
Thanks, added in 63ce7ea
