### ISSUE TITLE
New program repair paper and tool on ASE'19

### ISSUE THREAD

**Issue by xgdsmileboy** [program-repair/program-repair.github.io#30]
I would like to add the following publication 

- DOI: [10.1109/ASE.2019.00033](https://doi.org/10.1109/ASE.2019.00033)

and the corresponding tool:

- Name: GenPat
- One line description: Inferring program transformation from historical bug fixes via big code
- Target: [Java]
- DBPL key: 
- Website: 
- Repository (optional): https://github.com/xgdsmileboy/GenPat

**Comment by mechtaev** [comment]
Thanks, I will add it when the paper appears in dblp.

**Comment by xgdsmileboy** [comment]
DBPL key: conf/kbse/JiangRXZ19
Thanks.

**Comment by mechtaev** [comment]
Added in 02d27348103f2af15fb8563e273b88425be6a778
