### ISSUE TITLE
PraPR

### ISSUE THREAD

**Issue by ali-ghanbari** [program-repair/program-repair.github.io#35]
I would like to add the following tool:

- Name: PraPR
- One line description: fast JVM bytecode-level, template-/mutation-based APR
- Target: JVM Languages (e.g., Java, Kotlin, etc.)
- DBPL key:
      https://dblp.org/rec/conf/issta/GhanbariBZ19.html
      https://dblp.org/rec/conf/kbse/GhanbariZ19.html
- Website: https://github.com/prapr/prapr
- Repository (optional):

**Comment by mechtaev** [comment]
Added in 8d0b180. Thank you!
