### ISSUE TITLE
New program repair related paper on ISSRE’19

### ISSUE THREAD

**Issue by Emilyaxe** [program-repair/program-repair.github.io#36]
I would like to add the following publication:
- DOI:  10.1109/ISSRE.2019.00016
- DBLP key:  conf/issre/LiangHZ0X019

[08987552.pdf](https://github.com/program-repair/program-repair.github.io/files/4229997/08987552.pdf)

**Comment by mechtaev** [comment]
Added in db3cc0b. Thank you!
