### ISSUE TITLE
ssFix (ASE17)

### ISSUE THREAD

**Issue by dlee992** [program-repair/program-repair.github.io#38]
I would like to add the following tool:

- Name: ssFix
- One line description: Syntax-directed Code Search-Based Automated Repair Tool
- Target: Java
- DBPL key: conf/kbse/XinR17
- Website: https://github.com/qixin5/ssFix
- Repository (optional): https://github.com/qixin5/ssFix

**Comment by mechtaev** [comment]
Added in b73d432. Thank you!
