### ISSUE TITLE
Adding large dataset of (in)correct Python programs by students

### ISSUE THREAD

**Issue by umairzahmed** [program-repair/program-repair.github.io#44]
I would like to add the following benchmark:

- Name: Refactory
- One line description: program repair evaluation dataset of 1783 buggy and 2442 correct student submissions for 5 Python programming assignments 
- Target: Python
- DBPL key: [conf/kbse/HuAMLR19]
- Website: https://github.com/githubhuyang/refactory
- Repository (optional): https://github.com/githubhuyang/refactory

**Comment by mechtaev** [comment]
Added in 82bc9f4. Thanks!
