### ISSUE TITLE
DLFix: context-based code transformation learning for automated program repair. ICSE 2020

### ISSUE THREAD

**Issue by davidswresearcher** [program-repair/program-repair.github.io#46]
I would like to add the following publication:

Yi Li, Shaohua Wang, Tien N. Nguyen:
DLFix: context-based code transformation learning for automated program repair. ICSE 2020: 602-614

with a DBLP key: conf/icse/Li0N20

**Comment by mechtaev** [comment]
Thanks, it is added.

**Comment by davidswresearcher** [comment]
thank you
