### ISSUE TITLE
Add a new publication 

### ISSUE THREAD

**Issue by ShangwenWang** [program-repair/program-repair.github.io#52]
I would like to add the following publication:
Yihao Qin, Shangwen Wang, Kui Liu, Xiaoguang Mao, Tegawendé F. Bissyandé:
On the Impact of Flaky Tests in Automated Program Repair. SANER 2021: 295-306

- DBLP key: [SANER2021]
https://dblp.org/rec/conf/wcre/QinW0MB21.html

**Comment by mechtaev** [comment]
Added in 7e6c09e. Sorry for the delay.
