### ISSUE TITLE
Add ICML 2021 paper: conf/icml/BerabiHRV21

### ISSUE THREAD

**Issue by LostBenjamin** [program-repair/program-repair.github.io#54]
I would like to add the following publication:

- DBLP key: conf/icml/BerabiHRV21
- Title: TFix: Learning to Fix Coding Errors with a Text-to-Text Transformer
- Conference: ICML 2021
- Authors: Berkay Berabi, Jingxuan He, Veselin Raychev, Martin T. Vechev

Thanks!

**Comment by mechtaev** [comment]
Added in a0274c1, thank you!
