### ISSUE TITLE
Would you please add my publication? Thanks!

### ISSUE THREAD

**Issue by Emilyaxe** [program-repair/program-repair.github.io#59]
I would like to add the following publication:

Interactive Patch Filtering as Debugging Aid
- DBLP key: [conf/icsm/LiangJJZL0021]

**Comment by mechtaev** [comment]
Thanks! Added in [852501c](https://github.com/program-repair/program-repair.github.io/commit/852501c921afee3de36bd3ef74d9b4ea16e1a7f0)
