### ISSUE TITLE
C-Pack-IPAs

### ISSUE THREAD

**Issue by pmorvalho** [program-repair/program-repair.github.io#66]
I would like to add the following benchmark:

- Name: C-Pack-IPAs
- One line description: A C90 Program Benchmark of Introductory Programming Assignments
- Target: C (C90)
- DBPL key: journals/corr/abs-2206-08768
- Website: https://github.com/pmorvalho/C-Pack-IPAs
- Repository (optional): https://github.com/pmorvalho/C-Pack-IPAs

**Comment by Kui-Liu** [comment]
@pmorvalho Could you create a PR for it?
