### ISSUE TITLE
Adding paper "HIPPODROME: Data Race Repair using Static Analysis Summaries"

### ISSUE THREAD

**Issue by yannicnoller** [program-repair/program-repair.github.io#68]
I would like to add the following publication:

- DBLP key: journals/corr/abs-2108-02490

**Comment by yannicnoller** [comment]
opened PR https://github.com/program-repair/program-repair.github.io/pull/72

**Comment by mechtaev** [comment]
From @yannicnoller's comments

> Name: HIPPODROME
> One line description: statically detects and fixes data race conditions for small to large scale Java programs
> Target: Java
> DBPL key: journals/corr/abs-2108-02490
> Website: https://github.com/verse-lab/hippodrome
> Repository (optional): https://github.com/verse-lab/hippodrome

**Comment by mechtaev** [comment]
Thanks, added in [8abb808](https://github.com/program-repair/program-repair.github.io/commit/8abb808c06c7704a3e476a398bfe15b63062113b)
