### ISSUE TITLE
Add tool "HIPPODROME"

### ISSUE THREAD

**Issue by yannicnoller** [program-repair/program-repair.github.io#69]
I would like to add the following tool:

- Name: HIPPODROME
- One line description: HIPPODROME statically detects and fixes data race conditions for small to large scale Java programs
- Target: Java
- DBPL key: journals/corr/abs-2108-02490
- Website: https://github.com/verse-lab/hippodrome
- Repository (optional): https://github.com/verse-lab/hippodrome

**Comment by Kui-Liu** [comment]
@yannicnoller It would be great. Thank you!
