### ISSUE TITLE
feature: generate rss.xml

### ISSUE THREAD

**Issue by monperrus** [program-repair/program-repair.github.io#7]
Hi all,

In addition to generating we could generate a file `rss.xml` that we would then use in our favorite feed readers.

WDYT?

**Comment by mechtaev** [comment]
Hi Martin,

Our website already provides email notifications for the "Latest News". If you find RSS more convenient, you can integrate it with the build script.

Sergey

**Comment by monperrus** [comment]
The "latest news" are automatically re-generated for each addition?

**Comment by mechtaev** [comment]
Latest news aggregate latest papers and tools from high-impact conferences. It may be difficult to do completely automatically.
