### ISSUE TITLE
Add ITSP benchmark

### ISSUE THREAD

**Issue by umairzahmed** [program-repair/program-repair.github.io#70]
I would like to add the following benchmark:

- Name: ITSP
- One line description: A parallel corpus of 661 buggy-repaired program pairs submitted by CS-1 students for 74 unique assignments spread across 10 course weeks
- Target: C
- DBPL key: conf/sigsoft/YiAKTR17
- Website: https://github.com/jyi/ITSP#dataset-student-programs
- Repository (optional): https://github.com/jyi/ITSP

**Comment by Kui-Liu** [comment]
@umairzahmed Could you create a PR for it?

**Comment by mechtaev** [comment]
Thanks, added in [73d7205](https://github.com/program-repair/program-repair.github.io/commit/73d7205721865e90fe744b93ba8024c25a567096)
