### ISSUE TITLE
add CPR

### ISSUE THREAD

**Issue by rshariffdeen** [program-repair/program-repair.github.io#75]
I would like to add the following tool:

- Name: CPR
- One line description: detecting and discarding over-fitting patches via systematic co-exploration of the patch space and input space
- Target: C/C++
- DBPL key: conf/pldi/ShariffdeenNGR21
- Website: cpr-tool.github.io
- Repository (optional): https://github.com/rshariffdeen/cpr

**Comment by mechtaev** [comment]
Thanks, added in [73d7205](https://github.com/program-repair/program-repair.github.io/commit/73d7205721865e90fe744b93ba8024c25a567096)

**Comment by mechtaev** [comment]
Need to fix URL

**Comment by mechtaev** [comment]
URL fixed in 469b53135b3b48e6b48265583bafa876bba6f628
