### ISSUE TITLE
Add PatchWeave

### ISSUE THREAD

**Issue by rshariffdeen** [program-repair/program-repair.github.io#76]
I would like to add the following tool:

- Name: PatchWeave
- One line description: automated patch transplantation for semantically equivalent programs 
- Target: C/C++
- DBPL key: journals/tosem/ShariffdeenTGR21
- Website: https://patchweave.github.io/
- Repository (optional): https://github.com/rshariffdeen/patchweave

**Comment by mechtaev** [comment]
Thanks, added in [73d7205](https://github.com/program-repair/program-repair.github.io/commit/73d7205721865e90fe744b93ba8024c25a567096)
