### ISSUE TITLE
Please add the publication and tool details for SOSRepair

### ISSUE THREAD

**Issue by manishmotwani3** [program-repair/program-repair.github.io#88]
I would like to add the following tool:

- Name: SOSRepair
- One line description: Expressive semantic search-based technique for real-world program repair.
- Target:  C/C++
- DBPL key: journals/tse/AfzalMSBG21
- Website: https://github.com/squaresLab/SOSRepair
- Repository (optional): https://github.com/squaresLab/SOSRepair

**Comment by mechtaev** [comment]
Thanks, added in [a651bb6](https://github.com/program-repair/program-repair.github.io/commit/a651bb623feb44aa1fef885f4be45fce214f2915)
