### ISSUE TITLE
please add the publication and tool details for JaRFly - Java repair framework

### ISSUE THREAD

**Issue by manishmotwani3** [program-repair/program-repair.github.io#89]
I would like to add the following tool:

- Name: JaRFly
- One line description:  a Java Repair Framework for implementing automated repair tools for Java programs. 
- Target: Java
- DBPL key: journals/tse/MotwaniSBJG22
- Website: https://github.com/squaresLab/genprog4java/
- Repository (optional): https://github.com/squaresLab/genprog4java/

**Comment by mechtaev** [comment]
Thanks, added in 44e8e4ce2787ae48a27b52b6f57eeb188bded699
