### ISSUE TITLE
Program Repair with Repeated Learning

### ISSUE THREAD

**Issue by maxpei** [program-repair/program-repair.github.io#91]
I would like to add the following publication:

- doi: 10.1109/TSE.2022.3164662

**Comment by mechtaev** [comment]
Thanks, I will add it when it appears on DBLP.

**Comment by mechtaev** [comment]
Thanks added in [e3dff0c](https://github.com/program-repair/program-repair.github.io/commit/e3dff0c6fa669c8445da02bf95b65c6b036199c3).
