### ISSUE TITLE
Reduction of information flow leakage using GI

### ISSUE THREAD

**Issue by justynapt** [program-repair/program-repair.github.io#93]
I would like to add the following two publications, thank you:

- DBLP key: https://dblp.uni-trier.de/rec/conf/kbse/MesecanB0CP22.html?view=bibtex
- DBLP key: https://dblp.uni-trier.de/rec/conf/kbse/MesecanBCCP21.html?view=bibtex

**Comment by mechtaev** [comment]
Thanks, added in [e3dff0c](https://github.com/program-repair/program-repair.github.io/commit/e3dff0c6fa669c8445da02bf95b65c6b036199c3).
