### ISSUE TITLE
New deep neural network repair paper and tool published on ASE'22

### ISSUE THREAD

**Issue by xgdsmileboy** [program-repair/program-repair.github.io#97]
I would like to add the following tool:

Name: Dare
One line description: Repair deep neural networks for defending against diverse adversarial attacks
DBPL key: conf/kbse/ZhangWJYC22
Website: https://doi.org/10.5281/zenodo.7018397
Repository (optional):

**Comment by mechtaev** [comment]
Thanks, added in [60e8db9](https://github.com/program-repair/program-repair.github.io/commit/60e8db930fb3aeed1113fa20bc11a60a1a0e2403)
