### ISSUE TITLE
CETI

### ISSUE THREAD

**Issue by nguyenthanhvuh** [program-repair/program-repair.github.io#99]
I would like to add the following tool:

- Name: CETI (Correcting Errors using Test-Input Generation)
- One line description: Fixing C program errors using the KLEE input generation tool
- Target: C 
- DBPL key: conf/tacas/NguyenWKF17
- Website: https://github.com/dynaroars/ceti
- Repository (optional): https://github.com/dynaroars/ceti

**Comment by mechtaev** [comment]
Thanks, added in [f69ce2a](https://github.com/program-repair/program-repair.github.io/commit/f69ce2a122de82d5f63779e949317d776bd78e87)
